adds new messages
Toumash/hearty pull request #20
Opened 2020-03-29 20:13 UTC by AlicjaDobrzeniecka

2020-03-29 20:36 UTC, Toumash commented
@AlicjaDobrzeniecka what happens when i click the notification, not the buttons?

2020-03-29 20:42 UTC, Toumash requested changes

2020-03-29 20:42 UTC, Toumash commented on public/sw.js
> +        body: 'New heart notification!',
I would change this message to something more elegant like 'New message from your partner'

2020-03-30 16:18 UTC, AlicjaDobrzeniecka commented
> @AlicjaDobrzeniecka what happens when i click the notification, not the buttons?

When the user clicks the notification or the check heart button it should lead to same place - web page with the information of the sender and heart. It will appear in next PR.

2020-04-01 14:22 UTC, merged